services:
    nginx:
        container_name: albertclo_nginx
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ../../:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - albertclo-network

    php:
        container_name: albertclo_php
        build:
            args:
                user: ${OS_USER}
                uid: ${OS_UID}
                groupId: ${OS_GROUP_ID}
            context: ./php
            dockerfile: Dockerfile
        volumes:
            - ../../:/var/www
        depends_on:
            - pgsql
        networks:
            - albertclo-network

    pgsql:
        container_name: albertclo_postgres
        image: postgres:15
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - albertclo_postgres_data:/var/lib/postgresql/data
        networks:
            - albertclo-network

    node:
        container_name: albertclo_node
        build:
            args:
                user: ${USER:-ec2-user}
                uid: ${UID:-10002}
            context: ./node
            dockerfile: Dockerfile
        volumes:
            - ../../:/var/www
        working_dir: /var/www
        command: tail -f /dev/null  # Used to keep the docker container running. If this isn't here, the container will exit immediately after starting.
        networks:
            - albertclo-network

    redis:
        container_name: albertclo_redis
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - albertclo-network

volumes:
    albertclo_postgres_data:

networks:
  albertclo-network:
    driver: bridge
