name: Deploy to EC2
on:
    push:
        branches:
            - main
jobs:
    send-ssm-command:
        runs-on: ubuntu-latest

        steps:
            name: Checkout code
              - uses: actions/checkout@v2

              - name: Configure AWS credentials
                uses: aws-actions/configure-aws-credentials@v1
                with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

              - name: Send SSM Command
                run: |
                    export HOME=/home/ec2-user
                    sudo mkdir -p /opt/albertclo.com && \
                    sudo chown -R ec2-user:ec2-user /opt/albertclo.com && \
                    cd /opt/albertclo.com && \
                    if [ ! -d .git ]; then
                        git clone https://github.com/AlbertClo/albertclo.com.git .
                    fi && \
                    git config --global --add safe.directory /opt/albertclo.com && \
                    git remote set-url origin https://github.com/AlbertClo/albertclo.com.git && \
                    git add -A && git reset HEAD --hard && \
                    git checkout main && \
                    git fetch origin && \
                    git reset --hard origin/main && \
                    docker-compose --env-file .env -f infra/docker/docker-compose.yml exec php php artisan migrate && \
                    docker-compose --env-file .env -f infra/docker/docker-compose.yml exec php composer install
