name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::905418238199:role/albertclo-github-actions-deploy-role
        aws-region: us-east-1
        role-session-name: GitHubActionsSession
        audience: sts.amazonaws.com

    - name: Deploy to EC2 using SSM
      run: |
        INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=albertclo.com" --query "Reservations[].Instances[].InstanceId" --output text)
        aws ssm send-command \
          --instance-ids $INSTANCE_ID \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy latest changes" \
          --parameters commands=[
            "cd /opt/albertclo.com",
            "touch test1"
          ] \
          --output text

    - name: Wait for deployment to complete
      run: sleep 60
